# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  dockerRegistryServiceConnection: 'EntreprendreEnsemble-Mecena-acr'
  imageRepository: 'entreprendre-ensemble-front'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Packaging
  displayName: front packaging
  jobs:  
  - job: Packaging
    displayName: Front packaging
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.13.2'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build 
      displayName: 'npm install and build EntreprendreEnsemble-front'

    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/build/
        artifact: build


- stage: Build
  displayName: Docker image build
  jobs:  
  - job: Docker
    displayName: Docker image build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build
        path: $(Build.SourcesDirectory)/build/
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest